"""Blur 'plates' that hide hard-coded Chinese text: a soft bokeh / motion-blur gradient (like a blurred forest photo)
laid over a real FFmpeg blur. Generated by Qt, so the preview and the export look the same."""
import random
from PySide6.QtCore import Qt, QRectF
from PySide6.QtGui import QColor, QImage, QLinearGradient, QPainter, QBrush

PLATES = {   # dark base, mid, highlight, spot
    "Forest": ("#0f2420", "#335f2b", "#bccb3b", "#3aa4dc"),
    "Warm":   ("#2a0f06", "#b4481b", "#ffb347", "#ffe2b0"),
    "Ocean":  ("#06152a", "#0d4f8b", "#27c2e8", "#a6ecff"),
    "Violet": ("#150a2b", "#5b21b6", "#c026d3", "#60a5fa"),
    "Frost":  ("#c9d4e0", "#eef3f8", "#ffffff", "#b3c5d9"),
    "Night":  ("#04060c", "#0b1224", "#16264a", "#1e3a8a"),
    "Black":  ("#000000", "#000000", "#000000", "#000000"),
}
BLUR_ONLY = "Blur only"


def make_plate(style, w, h, alpha=0.9, seed=11):
    """Soft bokeh gradient QImage (w x h, ARGB). alpha = how much it covers what is under it."""
    w, h = max(8, int(w)), max(8, int(h))
    c0, c1, c2, c3 = [QColor(c) for c in PLATES.get(style, PLATES["Forest"])]
    sw = 110; sh = max(20, int(sw * h / w))
    small = QImage(sw, sh, QImage.Format_ARGB32); small.fill(0)
    p = QPainter(small); p.setRenderHints(QPainter.Antialiasing | QPainter.SmoothPixmapTransform)
    g = QLinearGradient(0, 0, sw, sh); g.setColorAt(0.0, c0); g.setColorAt(0.55, c1); g.setColorAt(1.0, c0)
    p.fillRect(0, 0, sw, sh, QBrush(g)); p.setPen(Qt.NoPen)
    rnd = random.Random(seed + len(style))
    for _ in range(5):                                  # long soft motion streaks
        col = QColor(c2); col.setAlpha(rnd.randint(70, 130)); p.setBrush(col)
        sx, sy = rnd.uniform(0.0, 0.5) * sw, rnd.uniform(0.0, 0.85) * sh
        p.drawEllipse(QRectF(sx, sy, rnd.uniform(0.5, 0.95) * sw, rnd.uniform(0.18, 0.4) * sh))
    for _ in range(4):                                  # bokeh spots
        col = QColor(c3 if rnd.random() < 0.5 else c2); col.setAlpha(rnd.randint(90, 170)); p.setBrush(col)
        d = rnd.uniform(0.16, 0.3) * sh
        p.drawEllipse(QRectF(rnd.uniform(0, 0.85) * sw, rnd.uniform(0, 0.7) * sh, d * 1.3, d))
    p.end()
    big = small.scaled(w, h, Qt.IgnoreAspectRatio, Qt.SmoothTransformation)     # the upscale = the blur
    out = QImage(w, h, QImage.Format_ARGB32); out.fill(0)
    q = QPainter(out); q.setOpacity(max(0.05, min(1.0, alpha))); q.drawImage(0, 0, big); q.end()
    return out


def make_feather_mask(w, h, path, feather=0.28):
    """Grayscale PNG (white inside, soft fade at the edges) used as the alpha of a blur box."""
    import numpy as np
    from PySide6.QtGui import QImage
    w, h = max(8, int(w)), max(8, int(h))
    f = max(6.0, min(w, h) * float(feather))
    x = np.minimum(np.arange(w), np.arange(w)[::-1]) / f
    y = np.minimum(np.arange(h), np.arange(h)[::-1]) / f
    m = np.clip(np.outer(np.clip(y, 0, 1), np.clip(x, 0, 1)), 0, 1)
    m = (np.sqrt(m) * 255).astype("uint8")                    # sqrt: stays strong over the text, fades only at the very edge
    img = QImage(m.data, w, h, w, QImage.Format_Grayscale8).copy()
    return img.save(path)
